FEW_SHOT_EXAMPLES = {
    "https://wikipedia.com": [
        ("SH 218 splits from I-35 just west of the I-35/Loop 1604 interchange in Live Oak and heads towards the east-southeast. About a half mile from I-35, SH 218 intersects Loop 1604 via a diamond interchange. The highway continues towards the southeast through Universal City, until it ends at FM 78 at the main gate of Randolph Air Force Base after just 3.99 miles (6.42 km).", "The SH 218 highway ends at the main gate of Randolph Air Force Base."),
        ("Hellenic Petroleum operates three refineries in Greece, in Thessaloniki, Elefsina and Aspropyrgos, which account for 57% of the refining capacity of the country (the remaining 43% belongs to Motor Oil Hellas). Also owns OKTA facilities in Skopje, Republic of North Macedonia for transportation and marketing of petroleum products. Crude oil for the refineries is supplied from Saudi Arabia, Iraq, Iran, Libya and Russia. The company also operates over 1700 gas stations in Greece under the BP and EKO brands, and about 300 gas stations in Serbia, Bulgaria, Cyprus, Montenegro and the Republic of North Macedonia. It also has a network which sells LPG, jet fuel, naval fuels and lubricants.", "Hellenic Petroleum operates over 1700 gas stations in Greece."),
        ("On 19 September 2013, it was announced that Michael Fassbender, Kodi Smit-McPhee, and Ben Mendelsohn had joined the cast of Slow West, produced by Film4 Productions.[8] Principal photography commenced on 21 October 2013 in New Zealand, which stood in for the film's Colorado setting.[9] The flashbacks set in the Scottish Highlands were filmed in Wester Ross.[10] Maclean, who is Scottish, \"felt the scenes in Scotland had to be shot there\" and not in New Zealand.[10]", "John Maclean is Scottish."),
   ],
    "https://reddit.com": [
        ("I read Allen Carr’s Easy Way to Stop Smoking. I promise I’m not being paid for this. The comedian Paul F Tompkins smoked for years but quit after reading this book, and would recommend it to anybody who wanted to try. I’m a big fan of his, so I decided it couldn’t hurt. As soon as I started the book, I realized what it was doing. I figured I was way too smart for it and that it would never work, even though I understood the points it was making and the psychology it was using. I continued to smoke as I was reading it, as the book instructs you to do, and was absolutely sure the cute little tricks it was using would never work and that I had just wasted ten bucks. I finished the book, threw away the unsmoked half of the pack I was on, and haven’t had so much as a craving since. I don’t even vape, I’ve had absolutely no cravings and no nicotine in any way for almost ten years now. I can not explain it but it worked immediately, in a way that nothing had worked up to that point, and wholeheartedly recommend it to anybody who is serious about quitting. ETA: Worth pointing out that's it's not a magic bullet and it doesn't work for everybody. To paraphrase a reply, it seems most effective on people who have a firm commitment to quitting but just haven't been able to make it stick for whatever reason. If you've tried everything but nothing's worked and you really, truly don't want to be a smoker anymore, it's worth a shot. ETA2: I just turned off notifications for this post because I really need to go to work and I'm getting like 10 replies a minute. I'm glad so many people have experienced success with this book and that so many others are interested in it! If you have questions, just read it!", "Paul F Tompkins was a longtime smoker."),
        ("I read an explanation a while back about this: basically Putin has made the military intentionally weak and disrespected so that he doesn’t have to worry about an uprising. People look down on them. They are treated like expendable trash. They are under armed and under trained. Separate from that Putin has a personal army that is only for protecting him. They are treated well and are screened for absolute loyalty.", "Vladimir Putin has a personal security detail."),
        ("I’ll likely be downvoted for this but this is just your standard straight down the middle athlete answer during media week, if you have a problem with the answer [which is fair] then it’s less about him as an individual and more about the NFL’s media training and stance as a whole. The same journalist asked everyone else the same question on both teams and they all answered pretty much the same. They do it to create as little headlines and distractions as possible before the big game. The only reason this may get more attention despite a similar neutral answer to everyone else is because of the TS connection. We have seen Trump speak negatively on both Travis and Taylor previously. As someone who isn’t much of a fan of his or the Chiefs he’s publicly supported and advocated for causes and groups that are diametrically opposed to Trump. Whether it be Kelce‘s public stance on guns, LGBT rights, BLM movement or vaccination. There is also a podcast appearance where he says Trump is racist, there was no positive comment made on Trump the individual in what was said in this answer.", "Trump has spoken negatively about Travis Kelce and Taylor Swift.")
    ],
    "https://nytimes.com": [
        ("Unlike major foreign policy announcements with past presidents, including Mr. Trump, the notion of the United States controlling Gaza had never been part of a public discussion before Tuesday. But privately, Mr. Trump had been talking about U.S. ownership of the enclave for weeks. And his thinking had accelerated, according to two administration officials, after his Middle East envoy, Steve Witkoff, returned from Gaza last week and described the horrific conditions there.", "Steve Witkoff is President Trump's Middle East envoy."),
        ("The virus that has been spreading through the nation’s dairies is a version of H5N1 known as B3.13, which has infected more than 950 herds in 16 states. Scientists believe that it initially jumped to cows from birds about a year ago, somewhere in the Texas panhandle. That transition took scientists by surprise, and this new one even more so. \"I was kind of under the belief that the bird-to-cow movement was a pretty rare event,\" said Richard Webby, an influenza expert at St. Jude Children’s Research Hospital.", "B3.13 is a strain of H5N1 that has infected more than 950 herds in 16 states."),
        ("It's the latest and most striking example of a trend that became turbocharged this year in which awards strategists who used to influence the race with targeted whisper campaigns have been caught flat-footed by controversies that originate online and quickly get out of hand. Now, Oscar season has become a decentralized free-for-all where social-media sleuths and determined fan armies dig up past gaffes, bad tweets and damaging clips, then amplify them on X, TikTok and awards-adjacent subreddits. That’s why, in the weeks leading up to the Oscar nominations, \"The Brutalist\" was pilloried on social media for using an A.I. speech tool to perfect the Hungarian spoken by star Adrien Brody, while \"Anora\" came under fire for failing to employ an intimacy coordinator. The ascendance of Brazilian best-actress nominee Fernanda Torres further boosted the bedlam, as her fan base on social media went after Gascón for implying that people associated with Torres were \"tearing me and 'Emilia Pérez' down.\" Days later, it was Torres who had to apologize when online Oscar obsessives resurfaced a 2008 clip of her performing in blackface on a Brazilian comedy show.", "The Brutalist was criticized for using A.I. speech tools."),
    ],
    "https://twitter.com": [
        ("Tesla sales have plummeted in Europe. By as much as 75% in some countries. Who here hopes Elon Musk loses EVERYTHING?", "Tesla shares have plummeted by as much as 75% in some European countries."),
        ("Adversarial ML research is evolving, but not necessarily for the better. In our new paper, we argue that LLMs have made problems harder to solve, and even tougher to evaluate. Here’s why another decade of work might still leave us without meaningful progress.", "LLMs have made problems harder to solve."),
        ("what’s the point of living in a surveillance culture if we can’t even get footage of Mitch McConnell getting his shit rocked by a staircase", "Mitch McConnell fell down the stairs."),
    ],
}
